2020-02-16 18:07:20,652 INFO: Microblog startup [in /home/stas/Projects/MyRestApi/app/__init__.py:51]
2020-02-16 18:07:39,415 ERROR: Exception on /edit_profile [POST] [in /home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/stas/Projects/MyRestApi/app/routes.py", line 94, in edit_profile
    db.session.commit()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('john', 'hei', 5)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-02-16 18:11:58,686 INFO: Microblog startup [in /home/stas/Projects/MyRestApi/app/__init__.py:51]
2020-02-16 18:12:46,951 INFO: Microblog startup [in /home/stas/Projects/MyRestApi/app/__init__.py:51]
2020-02-16 18:12:51,735 ERROR: Exception on /edit_profile [GET] [in /home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/stas/Projects/MyRestApi/app/routes.py", line 101, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile', form=form)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/stas/Projects/MyRestApi/app/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/stas/Projects/MyRestApi/app/templates/base.html", line 36, in top-level template code
    {% block content %}
  File "/home/stas/Projects/MyRestApi/app/templates/edit_profile.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask_wtf/form.py", line 134, in hidden_tag
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask_wtf/form.py", line 134, in <genexpr>
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/flask_wtf/form.py", line 124, in hidden_fields
    for f in fields:
  File "/home/stas/Projects/MyRestApi/venv/lib/python3.7/site-packages/wtforms/form.py", line 57, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
